# utils/utils.py

# YAML sections
SECTION_ERROR_CODES = 'error_codes'
SECTION_PARAMETERS = 'parameters'
SECTION_STATE_COMMANDS = 'state_commands'
SECTION_TEC_COMMANDS = 'tec_commands'
SECTION_TEC_STATE_COMMANDS = 'tec_state_commands'
SECTION_LOCK_STATUS_COMMANDS = 'lock_status'
SECTION_DEVICE_INFO = 'device_info'
SECTION_SYSTEM_COMMANDS = 'system'

# Parameter categories
CURRENT = "current"
VOLTAGE = "voltage"
TEMPERATURE = "temperature"
FREQUENCY = "frequency"

# Command and state register labels
RETRIEVE_DEVICE_ID_COMMAND = "0702"
STATE_OF_DEVICE_COMMAND = "state_of_device"
STATE_OF_TEC_COMMAND = "tec_state"
STATE_OF_INTERLOCK_COMMAND = "lock_status"

# Register names
REGISTER_DEVICE_ID = "device_id"
REGISTER_CURRENT = "current"
REGISTER_FREQUENCY = "frequency"
REGISTER_DURATION = "duration"
REGISTER_VOLTAGE = "voltage"
REGISTER_VOLTAGE_MEASURED = "voltage_measured"
REGISTER_CURRENT_MEASURED = "current_measured"
REGISTER_CURRENT_MIN = "current_min"
REGISTER_CURRENT_MAX = "current_max"
REGISTER_CURRENT_MAX_LIMIT = "current_max_limit"
REGISTER_CURRENT_PROTECTION_THRESHOLD = "current_protection_threshold"
REGISTER_CURRENT_SET_CALIBRATION = "current_set_calibration"

REGISTER_TEC_TEMPERATURE_MEASURED = "tec_temperature_measured"
REGISTER_TEC_TEMPERATURE_VALUE = "tec_temperature_value"
REGISTER_TEC_TEMPERATURE = "temperature"

REGISTER_PCB_TEMPERATURE_MEASURED = "pcb_temperature_measured"
REGISTER_TEC_CURRENT = "tec_current"
REGISTER_TEC_CURRENT_MEASURED = "tec_current_measured"
REGISTER_TEC_CURRENT_LIMIT = "tec_current_limit"
REGISTER_TEC_VOLTAGE = "tec_voltage"
REGISTER_NTC_COEFFICIENT = "ntc_b25_100_coefficient"
REGISTER_SERIAL_NUMBER = "serial_number"
REGISTER_TEC_P_COEFFICIENT = "p_coefficient"
REGISTER_TEC_I_COEFFICIENT = "i_coefficient"
REGISTER_TEC_D_COEFFICIENT = "d_coefficient"

# Bit codes for device state status (as hex strings)
OPERATION_STATE_STARTED = "0x0002"
CURRENT_SET_INTERNAL = "0x0004"
ENABLE_INTERNAL = "0x0010"
EXTERNAL_NTC_INTERLOCK_DENIED = "0x0040"
INTERLOCK_DENIED = "0x0080"

# Bit codes for tec state status (as hex strings)
TEC_OPERATION_STATE_STARTED = "0x0002"
TEC_SET_INTERNAL = "0x0004"
TEC_ENABLE_INTERNAL = "0x0010"

# Bitmask codes for lock state status (as hex strings)
LOCK_STATE_INTERLOCK = "0x0002"
LOCK_STATE_LD_OVERCURRENT = "0x0008"
LOCK_STATE_LD_OVERHEAT = "0x0010"
LOCK_STATE_EXTERNAL_NTC_INTERLOCK = "0x0020"
LOCK_STATE_TEC_ERROR = "0x0040"
LOCK_STATE_TEC_SELFHEAT = "0x0080"

# Start/Stop values
MODBUS_START_COMMAND_VALUE = 0x0008
MODBUS_STOP_COMMAND_VALUE = 0x0010

MODBUS_START_TEC_COMMAND_VALUE = 0x0008
MODBUS_STOP_TEC_COMMAND_VALUE = 0x0010
MODBUS_INTERNAL_TEMPERATURE_SET_COMMAND_VALUE = 0x0020
MODBUS_EXTERNAL_TEMPERATURE_SET_COMMAND_VALUE = 0x0040
MODBUS_INTERNAL_TEC_ENABLE_COMMAND_VALUE = 0x0200
MODBUS_EXTERNAL_TEC_ENABLE_SET_COMMAND_VALUE = 0x0400

MODBUS_DISABLE_INTERLOCK_COMMAND_VALUE = 0x2000
MODBUS_ENABLE_INTERLOCK_COMMAND_VALUE = 0x1000

# Log Levels
LOG_LEVEL_INFO = "INFO"
LOG_LEVEL_DEBUG = "DEBUG"
LOG_LEVEL_WARNING = "WARNING"
LOG_LEVEL_ERROR = "ERROR"

# Defaults
DEFAULT_PORT = "COM6"
DEFAULT_SLAVE_ADDRESS = 2
